I18n-and todo
tegnike/PORT pull request #10
Opened 2019-09-25 19:05 UTC by tegnike

2019-09-26 09:01 UTC, belion-freee requested changes
全体的にボタンやリンク名でベタ書きの箇所があるので、i18n管理下に置いてください。

2019-09-26 09:01 UTC, belion-freee commented on app/controllers/application_controller.rb
> +    def @path.is(*str)
この書き方でもいいですが、結局viewでif分岐を加えなければいけなくなりそうですね。
であれば、ymlで定義してhelperで参照すれば動的に設定できそうです。

```ruby
href_title = t(href_title)
href_title[controller.controller_name][controller.action_name]
```

```yml
ja:
  href_title:
    portforios: 
      index: "hoge"
      show: "mumu"
```

2019-09-26 09:01 UTC, belion-freee commented on app/controllers/application_controller.rb
> +      str.map { |s| self.include?(s) }.include?(true)
でもいけるかな。

```suggestion
      str.any? { |s| self.include?(s) }
```

2019-09-26 09:01 UTC, belion-freee commented on app/controllers/favorites_controller.rb
> +        flash.now[:alert] = "お気に入り登録に失敗しました。"
flashメッセージもymlで管理したほうがいいです。

2019-09-26 09:01 UTC, belion-freee commented on app/javascript/javascripts/application.js
> +    alert('ファイルサイズが5MBを超えています。');
### nits
こちらもDOMからメッセージ取得すればymlでメッセージを管理できますが、そこまでしなくていいかな。あと、gemもあるようですね。

https://github.com/fnando/i18n-js

2019-09-26 09:01 UTC, belion-freee commented on app/views/devise/mailer/email_changed.html.erb
> +  <p><%= t("we_re_contacting_you_to_notify_you_that_your_email_is_being_changed_to", email: @resource.unconfirmed_email) %></p>
key名はもっと短くていいです。ymlの階層構造で管理してください。

あと、Modelのコンテンツとか長い文章は別の方法で翻訳します。このくらいの長さならi18nの範疇ですが。
https://railsguides.jp/i18n.html#モデルのコンテンツを翻訳する

2019-09-26 09:01 UTC, belion-freee commented on app/views/shared/_error_messages.html.erb
> +      <%= object.errors.count %>件のエラーが発生したため投稿は保存されませんでした。
ここもymlで定義するべきだと思います。

2019-09-26 09:01 UTC, belion-freee commented on app/views/shared/_portfolio_form.html.erb
> +    <%= f.label "タイトル" %>
これもi18nで管理

2019-09-26 09:01 UTC, belion-freee commented on config/locales/devise.views.ja.yml
> +        we_re_contacting_you_to_notify_you_that_your_email_is_being_changed_to: "登録されているメールが%{email}に変更されたことをお知らせいたします。"
key名はもっと短くていいです。

2019-09-26 21:36 UTC, tegnike commented
対応いたしました。再度ご確認をお願いいたします。

2019-09-26 21:36 UTC, tegnike commented on app/controllers/application_controller.rb
> +    def @path.is(*str)
修正しました。

2019-09-26 21:36 UTC, tegnike commented on app/controllers/application_controller.rb
> +      str.map { |s| self.include?(s) }.include?(true)
上記を修正してこのメソッドは必要なくなったので削除しました。

2019-09-26 21:36 UTC, tegnike commented on app/controllers/favorites_controller.rb
> +        flash.now[:alert] = "お気に入り登録に失敗しました。"
修正しました。

2019-09-26 21:36 UTC, tegnike commented on app/javascript/javascripts/application.js
> +    alert('ファイルサイズが5MBを超えています。');
ここだけ日本語残しておくのも変なので、i18n-js gemで対応しました。

2019-09-26 21:36 UTC, tegnike commented on app/views/devise/mailer/email_changed.html.erb
> +  <p><%= t("we_re_contacting_you_to_notify_you_that_your_email_is_being_changed_to", email: @resource.unconfirmed_email) %></p>
deviseのkeyの命名記法に合わせたのですが、確かに長かったですよね。
修正しました。

2019-09-26 21:36 UTC, tegnike commented on app/views/shared/_error_messages.html.erb
> +      <%= object.errors.count %>件のエラーが発生したため投稿は保存されませんでした。
修正しました。

2019-09-26 21:36 UTC, tegnike commented on app/views/shared/_portfolio_form.html.erb
> +    <%= f.label "タイトル" %>
修正しました。

2019-09-26 21:36 UTC, tegnike commented on config/locales/devise.views.ja.yml
> +        we_re_contacting_you_to_notify_you_that_your_email_is_being_changed_to: "登録されているメールが%{email}に変更されたことをお知らせいたします。"
修正しました。

2019-09-27 01:35 UTC, belion-freee approved these changes
LGTM

2019-09-27 05:46 UTC, merged