Comment-model -> master
tegnike/PORT pull request #18
Opened 2019-10-13 23:07 UTC by tegnike

コメントモデルを作成しました。仕様は #17 に記載しています。
テストはまだ導入していませんので、CIはまだ通っていません。ご確認をお願いします。

質問がいくつかあります。
コードに記載していますので、ご確認、ご回答をお願いします。

2019-10-13 23:10 UTC, tegnike commented on app/models/comment.rb
> +  validates :evaluation, presence: true
評価機能（evaluation）を実装したいのですが、通常は必須項目、ただし自身の投稿には評価できないように設定したいです。
モデルのバリデーションにifをつけて管理しようとしたのですが、どうも上手くいきませんでした。
（評価する自身を判定するのにcurrent_userメソッドを用いたかったがモデルでは使用できないため）

ビューとコントローラーで何とか実装できると思いますが、そうなるとモデルレベルでのバリデーションが効かなくなってしまうので何となく嫌な感じがします。どうにかモデルで実装する方法はないでしょうか？

2019-10-13 23:13 UTC, tegnike commented on app/views/comments/_comment.html.erb
> + $('#comment-<%= comment.id %> .evaluation').raty({
webpackerが上手く機能していないようです。
ここのscriptの中身を `app/javascript/javascript/application.js` に書いてみたのですが、動作しませんでした。
何か誤っていますでしょうか？

2019-10-14 12:17 UTC, tegnike commented on app/views/comments/_comment.html.erb
> + $('#comment-<%= comment.id %> .evaluation').raty({
よく考えたらここ `<%= comment.id %>` とか使ってるので `app/javascript/javascript/application.js` から読み込むのは難しそうですかね。

2019-10-14 14:06 UTC, bishantakuma-abewadana commented on app/models/comment.rb
> +  validates :evaluation, presence: true
user_id持ってるので、portfolioのuser_idと同じであれば投稿者のコメントになるので、
アソシエーションをportfolioテーブルまで辿れば判別できないですかね。
もしくは、コメントと評価は別の機能なので、フィールドではなくて、テーブルとして管理するのが適切な気もします。

2019-10-14 14:10 UTC, belion-freee commented on app/models/comment.rb
> +  validates :evaluation, presence: true
user_id持ってるので、portfolioのuser_idと同じであれば投稿者のコメントになるので、
アソシエーションをportfolioテーブルまで辿れば判別できないですかね。
もしくは、コメントと評価は別の機能なので、フィールドではなくて、テーブルとして管理するのが適切な気もします。

2019-10-14 14:31 UTC, belion-freee reviewed
コメントしました。
メソッド名は前のでよかったと思いますよ。

2019-10-14 14:31 UTC, belion-freee commented on app/controllers/comments_controller.rb
> +      flash_failed_render
### nits
メソッドの処理の中で、renderしてないのでメソッド名は変えたほうがいいですね。

2019-10-14 14:31 UTC, belion-freee commented on app/controllers/comments_controller.rb
> +      flash_failed_redirect
### nits
これもメソッド名変えた方が良さげ

2019-10-14 14:31 UTC, belion-freee commented on app/views/comments/_comment.html.erb
> + $('#comment-<%= comment.id %> .evaluation').raty({
気づいた通り、 rubyコードをwebpack内では使えないので、javascriptに引数として渡すか、DOMの要素に含めるしかないですね。
エラーの内容分からないですが、今まで動いてたので、 `comment.id` 呼び出して失敗してたのだと思います。

2019-10-14 14:31 UTC, belion-freee commented on app/views/comments/_comment.html.erb
> + $('#comment-<%= comment.id %> .evaluation').raty({
こんな感じですかね。実際はexportとかしないといけないですが。

view
```ruby
someFunction('<%= comment.id %>')
```

webpacker
```webpacker(javascript)

function someFunction(comment_id) {
  // do something
}
```

2019-10-14 14:31 UTC, belion-freee commented on app/views/comments/_comment.html.erb
> + $('#comment-<%= comment.id %> .evaluation').raty({
ただこのくらいのソースならviewに書いていいと思います。rubyコードで取得するソース多いし。

2019-10-14 22:13 UTC, tegnike commented on app/models/comment.rb
> +  validates :evaluation, presence: true
> user_id持ってるので、portfolioのuser_idと同じであれば投稿者のコメントになるので、
アソシエーションをportfolioテーブルまで辿れば判別できないですかね

こちらの方法でいけました。考えてみたらその通りでしたね。
念の為、ビューとコントローラーでも入力制限をつけました。

2019-10-14 22:59 UTC, tegnike commented on app/views/comments/_comment.html.erb
> + $('#comment-<%= comment.id %> .evaluation').raty({
承知しました。では、今回はこのままで行きたいと思います。
いくつかのファイルに同じ記述があって少し嫌な感じしますが良しとしますかね。

2019-10-14 23:00 UTC, tegnike commented on app/controllers/comments_controller.rb
> +      flash_failed_render
メソッド名を少し変えました。
私も前の方が良かったと思うのですが、renderとredirectで少し処理を変えなくてはいけないことに気づき、やむを得なく修正しました。

2019-10-14 23:01 UTC, tegnike commented on app/controllers/comments_controller.rb
> +      flash_failed_redirect
同上です。

2019-10-14 23:01 UTC, tegnike commented
修正しました。改めてご確認をお願いします。

2019-10-15 01:33 UTC, belion-freee requested changes
CIコケてます。

このエラー自体は `try` で回避できますが、progressは絶対に入りそうな気がするのですが、テストデータの作成が不十分だったりしないでしょうか？

```
Failure/Error: self.user == self.progress.portfolio.user

NoMethodError:
  undefined method `portfolio' for nil:NilClass
./app/models/comment.rb:10:in `progress_owner?'
./spec/models/comment_spec.rb:14:in `block (4 levels) in <top (required)>'
./spec/rails_helper.rb:73:in `block (3 levels) in <top (required)>'
./spec/rails_helper.rb:72:in `block (2 levels) in <top (required)>'
```

2019-10-16 21:13 UTC, tegnike commented
テストを追加しました。改めてご確認をお願いします。

2019-10-17 05:57 UTC, belion-freee approved these changes
細かい指摘ばっかりなので承認します。

2019-10-17 05:57 UTC, belion-freee commented on app/views/comments/edit.js.erb
>  $("#comment-<%= @comment.id %>").html("<%= escape_javascript(render "comment_form") %>");
`app/views/comments/_comment_form.html.erb` に引数渡したい場合は `locales` オプション使っても渡せます。もしくは普通にHashで `id: "edit_comment"` でも渡せます。

2019-10-17 05:57 UTC, belion-freee commented on spec/system/comments_interface_spec.rb
> +        click_button "投稿"
### nits
`click_button`  割と不安定なので、 firstかfindでid指定で要素見つけて、 clickメソッド呼ぶ方が安定するかと思います。

2019-10-17 05:57 UTC, belion-freee commented on spec/system/progresses_index_spec.rb
> +          n += 1
rubyにもインクリメントできればいんですけどね。

2019-10-17 08:08 UTC, merged