User-function -> master
tegnike/PORT pull request #3
Opened 2019-09-09 10:41 UTC by tegnike

ユーザ機能が一通り実装できましたので、ご確認をお願いします。
テストに関してはまだ実装できていないので、後ほど追加します。

実装機能一覧
・ユーザー登録、ログイン機能全般、メール配信(devise)
・Twitter、Github（、Google）での外部サービスログイン(omniauth)
・画像アップロード(carrierwave) + S3
・管理画面（rails_admin）
・本番環境（heroku）における上記の設定

対象コミット
https://github.com/tegnike/PORT/commit/d28622a9f3b94f59b8255f15031cee0049035791 〜 https://github.com/tegnike/PORT/commit/1da19f29219adf73f0665a7d26e4591bf68ec89c

2019-09-09 11:22 UTC, belion-freee reviewed
ちょっと量が多かったので次回はもう少し絞っていただけると助かります。
例えば、admin画面は別プルリクとか。

2019-09-09 11:22 UTC, belion-freee commented on app/controllers/omniauth_callbacks_controller.rb
> +    end
条件以下にして、最後に `sign_in_and_redirect @user` した方がスッキリな気がします。

```
unless @user.persisted?
  @user.skip_confirmation!
  @user.save!
end
```

2019-09-09 11:22 UTC, belion-freee commented on app/javascript/stylesheets/application.scss
> +
このファイルはstylesheetのエンドポイントなので、スタイルの記述は別ファイルにして、importした方が構成的にはベターだと思います。

2019-09-09 11:22 UTC, belion-freee commented on app/models/ability.rb
> +# frozen_string_literal: true
rubocopの設定で自動で入力してそうですが、これは設定をfalseにして出力しない方がいいです。

2019-09-09 11:22 UTC, belion-freee commented on app/models/user.rb
> +      user.email = User.dumy_email(auth)
### nits
こっちの方がよく使いますね

```suggestion
      user.email =self.class.dumy_email(auth)
```

2019-09-09 11:22 UTC, belion-freee commented on app/models/user.rb
> +    def image_size
CarrierWaveで下記メソッドで定義できるので調べて見てください。

```
def size_range
  1..10.megabytes
end
```

2019-09-09 11:22 UTC, belion-freee commented on app/models/user.rb
> +      user.email = User.dumy_email(auth)
あと、ここってemailが取得できたらそっち入れてください。なかったらdummyを入力。

2019-09-09 11:22 UTC, belion-freee commented on app/views/devise/registrations/_user_form.html.erb
> +<script type="text/javascript">
個人的にこのくらいのソースならViewに直接書いていいと思いますが、webpackerの管理下で定義した方が体系的ですね。

2019-09-09 11:22 UTC, belion-freee commented on app/views/users/show.html.erb
> +<section class="fdb-block fp-active" data-block-type="testimonials" style="background-color: skyblue;" data-id="1">
### nits
あとでリファクタリングするかと思いますが、本来であればstyle要素は使わないでください。
このくらいの規模ならcssで今から定義してクラス指定した方が楽な気がします。あとでリファクタリングするより。

2019-09-09 11:22 UTC, belion-freee commented on config/initializers/redis.rb
> +REDIS ||= Redis.new(url: ENV["redis://redis:6379"] || "redis://localhost:6379")
### ASK

`ENV["redis://redis:6379"]` これENVにkey名じゃなくてvalue指定してません？

2019-09-09 11:22 UTC, belion-freee commented on db/migrate/20190908193647_add_admin_to_users.rb
> +class AddAdminToUsers < ActiveRecord::Migration[5.2]
これら4つは1つのマイグレーションにまとめていいですよ。新規追加なので。

2019-09-09 15:19 UTC, tegnike commented
修正したファイル群をコミットしました。
改めてご確認をお願いします。

2019-09-09 15:20 UTC, tegnike commented on app/controllers/omniauth_callbacks_controller.rb
> +    end
確かにそうですね、気づいていませんでした。修正しました。

2019-09-09 15:20 UTC, tegnike commented on app/javascript/stylesheets/application.scss
> +
ファイルを分けました。

2019-09-09 15:23 UTC, tegnike commented on app/models/user.rb
> +    def image_size
知りませんでした。こちらの方が簡潔でいいですね。

2019-09-09 15:24 UTC, tegnike commented on app/views/devise/registrations/_user_form.html.erb
> +<script type="text/javascript">
application.js ファイルに書き換えました。ただ、なぜかコンソールに `application.js:1 Uncaught ReferenceError: $ is not defined` というエラーが出てしまいました。
jQuery の後に設定し直したのですが、原因がわかりません。ご確認いただけないでしょうか？

2019-09-09 15:25 UTC, tegnike commented on app/views/users/show.html.erb
> +<section class="fdb-block fp-active" data-block-type="testimonials" style="background-color: skyblue;" data-id="1">
修正しました。

2019-09-09 15:26 UTC, tegnike commented on config/initializers/redis.rb
> +REDIS ||= Redis.new(url: ENV["redis://redis:6379"] || "redis://localhost:6379")
確かにそのとおりですね。しっかり確認できていなかったのですが、ここの記述実はまだ利用していないようなので、一旦コメントアウトしました。
後ほど使う際（ランキング機能）で再度修正します。

2019-09-09 15:28 UTC, tegnike commented on db/migrate/20190908193647_add_admin_to_users.rb
> +class AddAdminToUsers < ActiveRecord::Migration[5.2]
migration file はDBの記録みたいなものだから、作ったのはそのままにしておいた方が良い、という記述を見かけたのでこのようにしていました。
実際の現場でも、同一モデルのmigration fileだったらまとめてしまっているものなのでしょうか？

2019-09-09 15:28 UTC, tegnike commented on app/models/user.rb
> +      user.email = User.dumy_email(auth)
修正しました。

2019-09-09 15:42 UTC, belion-freee commented on db/migrate/20190908193647_add_admin_to_users.rb
> +class AddAdminToUsers < ActiveRecord::Migration[5.2]
一度masterに入れた場合は別ファイルにします。
ですが、今回の場合はUserテーブルを作るマイグレーションですので、これはまとめて構わないです。
マイグレーションファイル運用の過程でめっちゃ増えるんでまとめれるならまとめた方がいいですね。そのほうがindexとか見易いですし。

2019-09-09 15:50 UTC, belion-freee commented on app/javascript/javascripts/application.js
> +$('#user_image').bind('change', function() {
このスコープだとjs読み込んでないからエラーになってますね。
`window.$ = require('jquery');` を先頭に追加してみてください。

2019-09-09 15:50 UTC, belion-freee commented on app/models/user.rb
> +    def size_range
これはimageuploaderに定義してください。

http://arthurxxx.hatenablog.com/entry/2018/03/08/222925

2019-09-09 15:51 UTC, belion-freee commented on app/views/devise/registrations/_user_form.html.erb
> +<script type="text/javascript">
追加のコメントに記載しました。

2019-09-09 16:48 UTC, tegnike commented on db/migrate/20190908193647_add_admin_to_users.rb
> +class AddAdminToUsers < ActiveRecord::Migration[5.2]
なるほど、理解しました。では一つにまとめておきます。

2019-09-09 16:52 UTC, tegnike commented on app/javascript/javascripts/application.js
> +$('#user_image').bind('change', function() {
追加したら動作しました。ありがとうございます。
ご指摘内容について確認しておきます。

2019-09-09 17:00 UTC, tegnike commented on app/models/user.rb
> +    def size_range
修正しました。

2019-09-09 17:19 UTC, tegnike commented
修正しました。ご確認をお願いします。

2019-09-12 09:26 UTC, belion-freee approved these changes

2019-09-13 12:41 UTC, tegnike commented
テストを追加しました。確認をお願いします。

2019-09-13 12:51 UTC, belion-freee commented on spec/requests/omniauth_callbacks_controller_spec.rb
> +      it "user has correct information" do
### nits
条件一緒なので同じitブロックでいいと思います。(メッセージ分けたいならこれでもいいです)

2019-09-13 12:51 UTC, belion-freee commented on spec/support/omniauth_macros.rb
> +  def auth_params_mock_no_email
### nits
一箇所でしか使わないならメソッド化しないほうがいいです。今後使うならこのままで。

2019-09-13 12:51 UTC, belion-freee commented on spec/system/users_login_spec.rb
> +        expect(page).to have_selector ".alert", text: "Invalid Email or password."
### nits
英語でのテキスト出力はあとで日本語化したほうがいいですね(I18n)

2019-09-13 12:51 UTC, belion-freee commented on spec/system/users_signup_spec.rb
> +      subject {
### nits
このsubjectの処理は上とほぼ同じなので、valueをletで定義して取得するとスッキリすると思います。

2019-09-13 12:55 UTC, belion-freee requested changes
### MUST
CIが失敗してるので、確認してください。
`Error connecting to Redis on redis:6379 ` redisへの接続エラー。
おそらくサービスをCIに追加してないのでは。

2019-09-13 14:17 UTC, tegnike commented on spec/requests/omniauth_callbacks_controller_spec.rb
> +      it "user has correct information" do
長くなりそうなので分けてみました。今回はこれでいきたいと思います。

2019-09-13 14:32 UTC, tegnike commented on spec/support/omniauth_macros.rb
> +  def auth_params_mock_no_email
以降も使うかなと思ったのですが、おそらく使わないので削除しました。
ついでにsubject使ってまとめました。

2019-09-13 14:33 UTC, tegnike commented on spec/system/users_login_spec.rb
> +        expect(page).to have_selector ".alert", text: "Invalid Email or password."
はい、そうですね。
その点に関しては、cssを適用する際に一緒に治そうかと思っています。

2019-09-13 14:33 UTC, tegnike commented on spec/system/users_signup_spec.rb
> +      subject {
1つにまとめました。

2019-09-13 14:38 UTC, tegnike commented
上記について修正しました。
また、CIについてredisコンテナを追加し忘れていたので設定を修正しました。

改めてご確認をお願いします。

2019-09-13 15:20 UTC, belion-freee approved these changes

2019-09-13 15:20 UTC, belion-freee commented
LGTM

2019-09-13 16:11 UTC, merged